version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: dev-database
    env_file:
      - ./backend/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init_sql:/docker-entrypoint-initdb.d
    networks:
      - dispatch-network

  api:
    build: ./backend/api
    container_name: api-service
    env_file:
      - ./backend/.env
    environment:
      MYSQL_HOST: dev-database
      MYSQL_PORT: 3306
      MYSQL_POOL_SIZE: 10
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api/:/app/
    networks:
      - dispatch-network

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - dispatch-network

volumes:
  mysql_data:

networks:
  dispatch-network:
    driver: bridge