services:
  mysql:
    image: mysql:latest
    container_name: dev-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./database/init_sql:/docker-entrypoint-initdb.d
  
  backend:
    build: ./backend
    container_name: backend-service
    env_file:
      - .env
    environment:
        MYSQL_HOST: dev-database
        MYSQL_PORT: 3306
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DB: ${MYSQL_DATABASE}
        MYSQL_POOL_SIZE: 10
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/